#!/usr/bin/env node
/*jshint node:true */

var path = require("path");
var forever = require('forever-monitor');
var rc = require("rc");
var pargs = process.argv.slice(2);

var options = (function(args) {
    'use strict';

    var r = {path: "./", forever: true};
    while(args.length){
        var a = args.shift();
        if (a.indexOf("--no-forever") > -1) {
            r.forever = false;
        }else 
        if (a.indexOf("/") > -1) {
            r.path = a;
        } else {
            r.app = a;
        }
    }
    return r;
})(pargs);

var Server = require("./lib/ParseServer");
var e = new Server(options.app, options.path, options.forever);
e.start();