#!/usr/bin/env node

var args = process.argv.slice(2);

var processArgs = function(args){
	var r = {path: "./"};
	while(args.length){
		var a = args.shift();
		if (a.indexOf("/") > -1) {
			r.path = a;
		}else{
			r.app = a;
		}
	}
	return r;
}

var c = processArgs(args);

var spawn = require('child_process').spawn;
//console.log(__dirname);
var env = process.env;
env.NODE_PATH=__dirname+":"+c.path+":"+__dirname+"/node_modules";
env.PARSE_APP_DIRECTORY="./";
//console.log(env);
//spawn("node", ["-e", "console.log(process.env); require('"+__dirname+"/index')"], {'stdio': 'inherit', env: env });
//"--watchDirectory", "./", "--watchIgnore", ".*","-w"
spawn("forever", ["-v", "-w", "--watchDirectory", c.path, __dirname+"/index.js", c.path, c.app], {'stdio': 'inherit', env: env });